basePath: /
definitions:
  Server:
    properties:
      city: {type: string}
      provider: {type: string}
      public_ip: {type: string}
      state: {type: string}
      zip_code: {type: string}
    type: object
host: 10.244.108.173:6002
info:
  x-21-implements: ['31c7a5f5cb76ad33771180fbca39dd20376c3439']
  contact: {email: nakamoto@nakamoto.com, name: Satoshi Nakamoto}
  description: Run a ping on demand for bitcoin.
  title: ping21
  x-21-category: utilities
  x-21-github-project-url: https://github.com/21dotco/ping21
  x-21-keywords: [ping, network]
  x-21-quick-buy: "$ 21 buy url http://<ZEROTIER IP>:6002/?uri=google.com"
  x-21-total-price: {max: 5, min: 5}
paths:
  /:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: Ping statistics and information on server location.
          schema:
            properties:
              ping:
                items: {type: string}
                type: array
              server: {$ref: '#/definitions/Server'}
            type: object
      summary: Return ping statistics between this device and a given domain
        or IP.
  /get:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: HTTP GET statistics and information on server location.
          schema:
            properties:
              get:
                elapsed_ms: {type: integer}
                reason: {type: string}
                status_code: {type: integer}
                type: object
              server: {$ref: '#/definitions/Server'}
            type: object
      summary: Return HTTP GET statistics between this device and a given URL.
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
